New Importer: evalita2009, SIWIS,MSPKA + utilities
MozillaItalia/DeepSpeech-Italian-Model pull request #113
Opened 2020-12-14 17:21 UTC by eziolotta

Hi,
this is  implementation of  **Evalita2009, SIWIS Database, MSPKA Corpus**  importer - see [#90](https://github.com/MozillaItalia/DeepSpeech-Italian-Model/issues/90)  

1) Importers extend the ArchiveImporter utility in **corpora_importer.py**

ArchiveImporter implements download + extract + resample mp3 / wav-> wav + csv (wav and csv is compatible with DeepSpeech training)

Specific importer contains only parsing logic of transcripts and searching for the corresponding audio path.
I tested code on Windows 10, Python 3.6.5.

2) The utility **corpora_collector.py** takes care of collecting imported data, by building a new aggregate dataset.

A test with corpora_collector and these 3 importers produce a total of 12.18h of audio divided into 9882 clips lasting less than 15 seconds.

2020-12-17 20:53 UTC, nefastosaturo commented on MITADS-Speech/corpora_importer.py
> +    def __init__(self,corpus_name,archive_url,data_dir=None,csv_append_mode=False):
```suggestion
    def __init__(self,corpus_name,archive_url,extract_dir=None, data_dir=None,csv_append_mode=False):
```

2020-12-17 20:55 UTC, nefastosaturo commented on MITADS-Speech/corpora_importer.py
> +        self.archive_name = archive_filename.rsplit('.', 1)[0]
```suggestion
        self.archive_name = archive_filename.rsplit('.', 1)[0]
        self.extract_dir = self.archive_name
        if extract_dir is not None:
            self.extract_dir = extract_dir        
```

2020-12-17 20:56 UTC, nefastosaturo commented on MITADS-Speech/corpora_importer.py
> +        self._maybe_extract(self.origin_data_path, self.archive_name, archive_path)
```suggestion
        self._maybe_extract(self.origin_data_path,self.extract_dir, archive_path)
```

2020-12-17 20:58 UTC, nefastosaturo commented on MITADS-Speech/corpora_importer.py
> +        extracted_path = os.path.join(target_dir, extracted_data)
```suggestion
```suggestion
    def _maybe_extract(self,target_dir, extract_dir, archive_path):
        # If target_dir/extract_dir does not exist, extract archive in target_dir
        extracted_path = os.path.join(target_dir, extract_dir)
```
```

2020-12-17 20:59 UTC, nefastosaturo commented on MITADS-Speech/siwis_importer.py
> +        text_dir = os.path.join(self.origin_data_path, self.archive_name, "text","IT")
```suggestion
        wav_dir  = os.path.join(self.origin_data_path, self.extract_dir, "wav","IT")
        text_dir = os.path.join(self.origin_data_path, self.extract_dir, "text","IT")
```

2020-12-17 21:00 UTC, nefastosaturo commented on MITADS-Speech/siwis_importer.py
> +    siwis_importer = SiwisImporter(corpus_name,archivie_url,  data_dir=data_dir)
```suggestion
    corpus_name=CORPUS_NAME
    archive_url = 'https://phonogenres.unige.ch/downloads/siwis_latest.zip'
    data_dir=None
    siwis_importer = SiwisImporter(corpus_name,archive_url,extract_dir="siwis_database", data_dir=data_dir)
```

2020-12-17 21:04 UTC, nefastosaturo requested changes
from siwis_latest.zip the extracted folder name is siwis_database. the _maybe functions will look to siwis_latest folder that will be always missed

2021-01-08 11:31 UTC, Mte90 commented
@nefastosaturo can you check this again?

2021-01-11 14:25 UTC, nefastosaturo reviewed
add also:

sudo apt install sox

2021-01-11 14:25 UTC, nefastosaturo commented on MITADS-Speech/corpora_importer.py
> +        self.archive_name = archive_filename.split('.', 1)[0]## FIX: archive name with extension .tar.gz
```suggestion
        # Make archive_name from archive_filename
        archive_filename = self.archive_url.rsplit('/', 1)[-1]
        # os.path.splitext:
        # tar.gz: will split ("file.name.tar",".gz")
        # but will split correctly "cnz_1.0.0.zip" into ("cnz_1.0.0","zip")
        self.archive_name = os.path.splitext(archive_filename)[0]
        if self.archive_filename.endswith(".tar"):
          self.archive_name = self.archive_name.replace(".tar","")
```

2021-01-11 14:25 UTC, nefastosaturo commented on MITADS-Speech/siwis_importer.py
> +        text_dir = os.path.join(self.origin_data_path, self.extract_dir, "text","IT")
```suggestion
        text_dir = os.path.join(self.origin_data_path, self.extract_dir, "txt","IT")
```

2021-01-11 14:25 UTC, nefastosaturo commented on MITADS-Speech/requirements.txt
> +sox
```suggestion
sox
charset_normalizer
```

2021-01-11 14:45 UTC, merged